export const NEIGHBOURHOODS = ["All Taipei", "Da-an", "Xinyi", "Zhongshan", "Shilin", "Beitou", "Songshan", "Wanhua", "Neihu", "Tamsui"];
export const BUDGETS = ["$ Budget (NT$0-300)", "$$ Medium (NT$300-800)", "$$$ Upscale (NT$800-2000)", "$$$$ Luxury (NT$2000+)"];
export const VIBES = ["Casual", "Romantic", "Adventurous", "Foodie", "Cultural", "Nightlife"];
export const TIMES = ["Any time", "Morning", "Afternoon", "Evening", "Late night"];

export const CATEGORY_KEYS = ["catFood", "catArts", "catCreative", "catEntertainment", "catActive", "catChill"] as const;

export const INTEREST_CATEGORIES = [
  {
    label: "Food & Drink",
    items: [
      "Night Market", "Night Market Crawl", "Street Food", "Food Tour", "Food Market",
      "Hotpot", "Shabu Shabu", "Seafood Hot Pot", "Sukiyaki", "Fondue Night",
      "Bubble Tea", "Mango Shaved Ice", "Ice Cream Walk", "Soft Serve Walk", "Taiyaki Walk",
      "Brunch", "Dim Sum Brunch", "Taiwanese Breakfast", "Waffle Café", "Crepe Café",
      "Ramen", "Dim Sum", "Vietnamese Pho", "Beef Noodle Soup", "Soup Dumplings",
      "Sushi Bar", "Omakase", "Yakitori Bar", "Robatayaki", "Teppanyaki",
      "Korean BBQ", "Izakaya", "Tonkatsu", "Gyoza Bar",
      "Pork Chop Rice", "Lu Rou Fan", "Oyster Pancake", "Scallion Pancake", "Stinky Tofu Challenge",
      "Fine Dining", "Michelin Dining", "Rooftop Dining", "Pop-up Dinner", "Dessert Omakase",
      "French Bistro", "Italian Trattoria", "Mediterranean Feast", "Curry Night", "Mexican Street Food",
      "Tapas Bar", "Oyster Bar", "Beef Burger Bar", "Pizza Night", "Charcuterie Date",
      "Craft Beer", "Draft Beer Pub", "Beer Garden",
      "Wine Tasting", "Wine Bar", "Natural Wine Bar", "Champagne Bar",
      "Cocktail Bar", "Sake Bar", "Sake Tasting", "Whisky Bar", "Whisky Tasting",
      "Gin Bar", "Rum Bar", "Mocktail Bar", "Listening Bar",
      "Specialty Coffee", "Espresso Bar", "Coffee Tasting", "Cold Brew Café",
      "Matcha Café", "Vegan Café", "Smoothie Bar", "Hot Chocolate Café",
      "Dessert Bar", "Pastry Tour", "Donut Café", "Cheese Board", "Bakery Hopping",
      "Cat Café", "Afternoon Tea", "Bubble Waffle",
      "Tteokbokki", "Korean Fried Chicken", "Bingsoo", "Tanghulu Walk", "Egg Tart Café",
      "Kimchi Making Class", "Cheese Making Class", "Braised Beef Brisket",
      "Steakhouse", "Wagyu Beef Dinner", "AYCE Buffet", "Hot Pot Buffet", "Vegetarian Restaurant",
      "Sports Bar", "Sky Bar", "Rooftop Bar", "Hotel Bar",
    ],
  },
  {
    label: "Arts & Culture",
    items: [
      "Art Gallery", "Photography Exhibition", "Pop Art Exhibition", "Illustration Exhibition", "Sculpture Garden",
      "Museum", "Night Museum", "Science Museum", "Design Museum", "Natural History Museum", "Toy Museum",
      "Film", "Art House Cinema", "Rooftop Cinema", "Outdoor Cinema", "Film Club",
      "Live Music", "Jazz Club", "Classical Concert", "Traditional Music Concert", "Open Mic Night",
      "Theater", "Dance Performance", "Opera Night", "Ballet Performance", "Street Performance",
      "Puppet Theater", "Shadow Puppet Show",
      "Comedy Show", "Stand-up Comedy", "Improv Show", "Drag Show", "Drag Brunch",
      "Poetry Slam", "Spoken Word Night", "Storytelling Night", "Roast Night",
      "Street Art Tour", "Mural Walk", "Graffiti Tour", "Light Art Installation", "Animation Exhibition",
      "Architecture Walk", "History Walk", "Photography Walk", "Night Photography Walk",
      "Temple Visit", "Indigenous Culture", "Cultural Festival", "Lantern Making", "Paper Cutting Art",
      "Tea Ceremony", "Calligraphy",
      "Vinyl Record Shop", "Record Store Digging", "Manga Café", "Anime Screening",
      "Antique Market", "Indie Market", "Zine Fair", "Craft Fair", "Flea Market",
      "Bookstore", "Book Café", "Library Date",
      "Fashion Show", "Cosplay Event", "Planetarium",
      "Illustration Class", "Rock Concert", "Indie Concert", "Electronic Music Night",
      "Music Festival", "Immersive Exhibition", "Art Fair",
    ],
  },
  {
    label: "Creative & Hands-on",
    items: [
      "Pottery Class", "Glass Blowing", "Stained Glass", "Mosaic Making",
      "Painting Workshop", "Watercolor Class", "Acrylic Pour", "Life Drawing Class",
      "Printmaking", "Screen Printing", "Linocut Printing", "Paper Marbling", "Cyanotype Printing",
      "Origami Workshop", "Origami Art Night", "Calligraphy Workshop", "Paper Cutting Art",
      "Terrarium Making", "Resin Art", "Polymer Clay Art", "Decoupage", "Collage Making",
      "Jewelry Making", "Wire Jewelry", "Leather Craft",
      "Candle Making", "Soap Making", "Perfume Blending",
      "Flower Arranging", "Ikebana",
      "Embroidery", "Weaving Workshop", "Macramé", "Felting Workshop",
      "Tie-dye Workshop", "Batik Workshop", "Natural Dyeing",
      "Cooking Class", "Sushi Making", "Pasta Making", "Bread Baking",
      "Baking Class", "Cake Decorating", "Macaron Making", "Cookie Decorating",
      "Chocolate Making", "Mochi Making", "Dumpling Making", "Jam Making",
      "Cocktail Making Class", "Beer Brewing Workshop", "Coffee Brewing Class",
      "Dance Class", "Ukulele Class", "Music Jam Session",
      "Kintsugi Workshop", "Bookbinding", "Stamp Carving", "Dreamcatcher Making",
      "Neon Sign Making", "Terrarium Date", "Film Photography",
      "Knitting Class", "Crochet Workshop", "Spray Paint Art", "Digital Art Workshop",
      "Botanical Illustration", "Ceramics Studio",
      "Creative Writing", "Zine Making Workshop", "DIY Craft",
    ],
  },
  {
    label: "Entertainment",
    items: [
      "Karaoke", "Escape Room", "VR Escape Room",
      "Bowling", "Arcade", "Retro Gaming Bar", "Claw Machine Café", "Pinball Bar",
      "VR Gaming", "Laser Tag", "Paintball", "Rage Room",
      "Mini Golf", "Glow Golf", "Billiards", "Ping Pong Bar", "Shuffleboard Bar", "Dart Bar",
      "Archery", "Axe Throwing", "Go-Kart Racing", "Shooting Range", "Batting Cage",
      "Trampoline Park", "Inflatable Park", "Ice Skating", "Roller Skating", "Skate Park",
      "Board Games", "Pub Quiz", "Trivia Night", "Trivia Bar Crawl",
      "Murder Mystery Dinner", "Dinner Theater", "Scavenger Hunt", "City Rally",
      "Magic Show", "Haunted House", "Circus Show",
      "Silent Disco", "Speed Dating", "Cosplay Meetup",
      "Amusement Park", "Waterpark",
      "Self Photo Studio", "Photo Booth Tour", "Night Bus Tour",
      "Puzzle Café", "Badminton", "Table Tennis", "Tennis",
      "E-Sports Café", "Rhythm Game", "Darts League",
      "Sports Viewing", "Immersive Theater", "Karaoke Box",
    ],
  },
  {
    label: "Active & Outdoor",
    items: [
      "Mountain Hiking", "Waterfall Hike", "Sunrise Hike", "Full Moon Hike", "Trail Running",
      "Yangmingshan Day Trip", "Elephant Mountain", "Maokong Gondola",
      "River Cycling", "Night Cycling", "Longboarding", "Scooter Tour",
      "Kayaking", "Stand-up Paddleboard", "Boat Trip", "Sunset Cruise",
      "Rock Climbing", "Zip Line", "Horseback Riding",
      "Picnic", "Cherry Blossom Picnic", "Beach Volleyball", "Frisbee Park", "Kite Flying",
      "Riverside Walk", "River Walk", "Coastal Walk", "Tree Canopy Walk", "Urban Exploration",
      "Bird Watching", "Firefly Watching", "Foraging Walk", "Outdoor Yoga",
      "Botanical Garden", "Butterfly Garden", "Sculpture Garden",
      "Hot Springs", "Glamping", "Camping", "Farm Visit", "Strawberry Picking",
      "Night Fishing", "Night Run", "Night Safari", "Beach Day",
      "Zoo Date", "Aquarium Visit",
      "Stargazing", "Meteor Shower Watch", "Sunset Watching", "Sunrise Watch", "Dawn Walk",
      "Cycling Tour", "E-bike Tour", "Swimming", "Wakeboarding", "Paddleboarding Tour",
      "Golf Driving Range", "Dragon Boat Racing", "Mountain Biking", "Running Club",
      "CrossFit", "Fitness Boot Camp", "Tai Chi", "Capoeira", "Aerial Arts",
      "Boxing Class", "Muay Thai Class", "Fencing Class", "Wrestling Class",
      "Indoor Skydiving", "Indoor Snowboarding", "Indoor Surfing",
      "Indoor Basketball", "Indoor Rock Climbing", "Bouldering",
      "Parkour Class", "Acrobatics Class", "Gymnastics Class",
      "Bungee Jumping", "Paragliding", "Hot Air Balloon",
      "Scuba Diving", "Snorkeling", "Freediving",
      "Surfing", "Kitesurfing", "Wakeskating",
      "BMX Park", "Skateboarding", "Longboarding Tour",
      "Jiufen Day Trip", "Danshui Old Street", "Lantern Festival", "MRT Hopping",
    ],
  },
  {
    label: "Chill & Wellness",
    items: [
      "Spa & Wellness", "Couples Massage", "Foot Massage", "Gua Sha Facial", "Couples Skincare",
      "Sauna", "Infrared Sauna", "Contrast Therapy", "Float Tank", "Sound Bath", "Hammam",
      "Yoga", "Hot Yoga", "Aerial Yoga", "Pilates Class", "Barre Class", "Breathwork", "Meditation Class",
      "Forest Bathing", "Reiki Session", "Chakra Workshop", "Herbal Tea Tasting",
      "Nail Art", "Crystal Shopping", "Plant Shopping", "Flower Market Visit",
      "Tarot Reading", "Astrology Reading", "Oracle Card Reading", "Aura Photography",
      "Journaling Café", "Garden Café", "Greenhouse Café", "Hammock Park",
      "Pet Café", "Rooftop Café", "Shopping", "Digital Detox Day", "Xinyi Nightlife",
      "Jimjilbang", "Korean Spa", "Bath Bomb Making", "Sound Healing", "Eye Mask Café",
      "Thai Massage", "Hot Stone Massage", "Aromatherapy", "Reflexology", "Acupuncture",
      "Traditional Chinese Medicine", "Body Scrub", "Facial Treatment",
      "Hair Spa", "Manicure & Pedicure", "Eyelash Extension", "Brow Lamination",
    ],
  },
];

export const ITEM_CONSTRAINTS: Record<string, { budgets?: string[]; times?: string[] }> = {
  "Sunrise Hike":       { times: ["Morning"] },
  "Sunrise Watch":      { times: ["Morning"] },
  "Dawn Walk":          { times: ["Morning"] },
  "Dim Sum Brunch":     { times: ["Morning", "Afternoon"] },
  "Taiwanese Breakfast":{ times: ["Morning", "Afternoon"] },
  "Brunch":             { times: ["Morning", "Afternoon"] },
  "Waffle Café":        { times: ["Morning", "Afternoon"] },
  "Outdoor Yoga":       { times: ["Morning", "Afternoon"] },
  "Karaoke":            { times: ["Evening", "Late night"] },
  "Xinyi Nightlife":    { times: ["Evening", "Late night"] },
  "Drag Show":          { times: ["Evening", "Late night"] },
  "Silent Disco":       { times: ["Evening", "Late night"] },
  "Pub Quiz":           { times: ["Evening", "Late night"] },
  "Trivia Night":       { times: ["Evening", "Late night"] },
  "Trivia Bar Crawl":   { times: ["Evening", "Late night"] },
  "Night Market Crawl": { times: ["Evening", "Late night"], budgets: ["$", "$$"] },
  "Night Museum":       { times: ["Evening"] },
  "Night Cycling":      { times: ["Evening", "Late night"] },
  "Night Run":          { times: ["Evening", "Late night"] },
  "Night Fishing":      { times: ["Evening", "Late night"] },
  "Night Safari":       { times: ["Evening", "Late night"] },
  "Night Photography Walk": { times: ["Evening", "Late night"] },
  "Full Moon Hike":     { times: ["Evening", "Late night"] },
  "Stargazing":         { times: ["Evening", "Late night"] },
  "Meteor Shower Watch":{ times: ["Late night"] },
  "Firefly Watching":   { times: ["Evening", "Late night"] },
  "Sunset Watching":    { times: ["Afternoon", "Evening"] },
  "Sunset Cruise":      { times: ["Afternoon", "Evening"] },
  "Live Music":         { times: ["Evening", "Late night"] },
  "Jazz Club":          { times: ["Evening", "Late night"] },
  "Cocktail Bar":       { times: ["Evening", "Late night"] },
  "Whisky Bar":         { times: ["Evening", "Late night"] },
  "Whisky Tasting":     { times: ["Evening", "Late night"] },
  "Listening Bar":      { times: ["Evening", "Late night"] },
  "Champagne Bar":      { times: ["Evening", "Late night"], budgets: ["$$$", "$$$$"] },
  "Sake Bar":           { times: ["Evening", "Late night"] },
  "Sake Tasting":       { times: ["Evening", "Late night"] },
  "Gin Bar":            { times: ["Evening", "Late night"] },
  "Rum Bar":            { times: ["Evening", "Late night"] },
  "Haunted House":      { times: ["Evening", "Late night"] },
  "Night Bus Tour":     { times: ["Evening", "Late night"] },
  "Speed Dating":       { times: ["Evening"] },
  "Circus Show":        { times: ["Afternoon", "Evening"] },
  "Opera Night":        { times: ["Evening"] },
  "Ballet Performance": { times: ["Afternoon", "Evening"] },
  "Michelin Dining":    { budgets: ["$$$", "$$$$"] },
  "Fine Dining":        { budgets: ["$$$", "$$$$"] },
  "Omakase":            { budgets: ["$$$", "$$$$"] },
  "Dessert Omakase":    { budgets: ["$$$", "$$$$"] },
  "Rooftop Dining":     { budgets: ["$$", "$$$", "$$$$"] },
  "Pop-up Dinner":      { budgets: ["$$$", "$$$$"] },
  "Fondue Night":       { budgets: ["$$", "$$$", "$$$$"] },
  "Charcuterie Date":   { budgets: ["$$", "$$$", "$$$$"] },
  "Street Food":        { budgets: ["$", "$$"] },
  "Night Market":       { budgets: ["$", "$$"] },
  "Stinky Tofu Challenge": { budgets: ["$", "$$"] },
  "Pork Chop Rice":     { budgets: ["$", "$$"] },
  "Lu Rou Fan":         { budgets: ["$", "$$"] },
  "Oyster Pancake":     { budgets: ["$", "$$"] },
  "Scallion Pancake":   { budgets: ["$", "$$"] },
  "Taiyaki Walk":       { budgets: ["$", "$$"] },
  "Soft Serve Walk":    { budgets: ["$", "$$"] },
};
